// This file is @generated by prost-build.
/// File
///
/// Fields :
///
/// - name: Name of the file
/// - type: Type of the file
/// - content: Content of the file
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    /// name: Name of the file
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// type: Type of the file
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    /// content: Content of the file
    #[prost(bytes = "vec", tag = "3")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
